name: Bug report
description: File a bug report if something is not working right.
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve Mega monitor!
  - type: checkboxes
    id: init
    attributes:
      label: "Before submitting a bug report, I have:"
      options:
        - label: Reviewed the documentation.
          required: true
        - label: Ensured I am using ghcr.io/mega-monitor/ docker repository.
          required: true
        - label: Ensured I am using the latest version.
          required: true
        - label: Enabled verbose logging.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What is the behavior?
      description: If applicable, mention what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Which operating system do you use?
      multiple: false
      options:
        - Windows
        - Linux
        - MacOS
        - Unraid
    validations:
      required: true
  - type: dropdown
    id: deployment
    attributes:
      label: What type of deployment do you use?
      multiple: false
      options:
        - Docker container
        - Binary (executable) file
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false