name: Build & publish containers

on:
  push:
    tags: ['v*.*.*']          
  workflow_dispatch:          

permissions:
  packages: write             
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive lower‑case owner
        id: vars
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"


      - name: Build & push mega-monitor container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.owner }}/mega-monitor:${{ github.ref_name }}
            ghcr.io/${{ steps.vars.outputs.owner }}/wmega-monitor:latest